### PR TITLE
Uncaught (in promise) Object

### PR DESCRIPTION
**Pull request by janschoenherr**
Fixes "Uncaught (in promise) Object" error message in Chrome.

### CODE REVIEW

**Comment by JosephSilber** [comment]
There's no need to "fix" this. That message is there for a reason.

**Comment by janschoenherr** [comment]
Could you shed some light on this? There does not seem to be a way to actually catch the error.

**Comment by yyx990803** [comment]
They can catch it on the returned promise. But why do we have `success` and `error` in here anyway? Imo we should just keep the standard compliant `then`, `catch`.

**Comment by janschoenherr** [comment]
```error```, ```success``` and ```always``` are simply nice shortcuts. Also, they provide a way, to stay in the ```this``` context of the calling function.

**Comment by yyx990803** [comment]
I mean, what's the difference between `success` vs. `then`, and `error` vs. `catch`? They seem to do mostly the same.

**Comment by yyx990803** [comment]
Oh I see, it destructures the response into flat args.

**Pull request merged**
